### ISSUE TITLE
user_authorities table isn't updated when adding new user

### ISSUE THREAD

**Issue by AleksandraKasznia** [pawelgalka/restaurant-io#7]
When adding a new user, table "user" is updated (new user is added), however, table "user_authorities" isn't so new users have no permissions.

**Comment by AleksandraKasznia** [comment]
I tried passing as "authorities": "ROLE_WAITER" or "WAITER" or "waiter" and none of this worked.

**Comment by pawelgalka** [comment]
pull request created
